spring:
  application:
    name: myro
  datasource:
    url: jdbc:mysql://localhost:3306/schedule
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jdbc.time_zone: Asia/Seoul
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  config:
    import: classpath:application-secret.yml